apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gol-deploy
  name: gol-deploy
spec:
  replicas: 4
  selector:
    matchLabels:
      app: gol-deploy
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: gol-deploy
    spec:
      containers:
      - image: yvak90/gameoflife:1.0
        name: gameoflife
        resources: {}
status: {}
