apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-deploy
  name: nginx-deploy
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30040
  selector:
    app: nginx-deploy
  type: NodePort
status:
  loadBalancer: {}
