apiVersion: v1
kind: Service
metadata:
  labels:
    app: jenkins-deploy
  name: jenkins-deploy
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 32100
  selector:
    app: jenkins-deploy
  type: NodePort
status:
  loadBalancer: {}
